[package]
name = "humojibake"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = { version = "0.3", default-features = false }
strum = { version = "0.22", features = ["derive"] }
utf8-chars = "1.0.2"
